project_name: natscli
version: 2

release:
  github:
    owner: nats-io
    name: natscli
  name_template: "Release {{.Version}}"
  draft: true
  prerelease: auto

changelog:
  disable: true

builds:
  - main: ./nats
    id: nats
    binary: nats
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - 386
      - s390x
    goarm:
      - 6
      - 7
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: 386

archives:
  - name_template: "nats-{{.Version}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    wrap_in_directory: true
    format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256

brews:
  - name: nats
    directory: Formula
    repository:
      owner: nats-io
      name: homebrew-nats-tools
      token: "{{ .Env.GITHUB_APP_TOKEN }}"
    url_template: "https://github.com/nats-io/natscli/releases/download/{{ .Tag }}/nats-{{.Version}}-{{ .Os }}-{{ .Arch }}{{if .Arm}}{{.Arm}}{{end}}.zip"
    homepage: "https://github.com/nats-io/natscli"
    description: "NATS utility"
    skip_upload: auto
    test: |
      system "#{bin}/nats --version"
    custom_block: |
      resource "zsh_completion" do
        url "https://get-nats.io/zsh.complete.nats"
        sha256 "2b0832b26b1644ff01a293dc1b91320fc24f818ad8e89dd416f9c83f23b4df59"
      end
    install: |
      bin.install "nats"
      (man1/"nats.1").write Utils.safe_popen_read(bin/"nats", "--help-man")
      resource("zsh_completion").stage do
        zsh_completion.install "zsh.complete.nats" => "_nats"
      end

nfpms:
  - file_name_template: 'nats-{{.Version}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}'
    homepage:  https://nats.io
    description: NATS Utility
    maintainer: R.I. Pienaar <rip@devco.net>
    license: Apache 2.0
    vendor: Synadia Inc.
    bindir: /usr/local/bin
    formats:
      - deb
      - rpm
